---
title: "HoopsR Tutorial"
author: "Sammy B"
date: "9/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# HoopsR Tutorial

The following program will be used to learn HoopsR by Saiem Gilani
<br>
https://saiemgilani.github.io/hoopR/articles/intro-to-hoopR.html
<br>
## Setup
```{r}
# import libraries
pacman::p_load_current_gh("saiemgilani/hoopR")
pacman::p_load(dplyr, ggplot2,animation,ggimage,png, glue)

# set browser login
browser <- login(Sys.getenv("KP_USER"), Sys.getenv("KP_PW"))
```
<br>
## Pull Ratings
Explanation of Ratings: https://kenpom.com/blog/ratings-explanation/
```{r}
# Get Pomeroy ratings for the last 10 years by using the
rtgs <- kp_pomeroy_ratings(min_year = 2010, max_year = 2020)
glimpse(rtgs)
```
## Processing
```{r}
team1 = "Notre Dame"
team2 = "ACC"
metric <- "adj_em" 
full_metric <- "Adjusted Efficiency Margin"
Color1 = '#C99700'
Color2 = 'navyblue'

rtgs$metric = rtgs[, metric]


# We will create a second rtgs dataset for the the filtered ACC data.
rtgs_acc <- rtgs %>% 
  dplyr::filter(.data$conf == team2) %>% 
  dplyr::group_by(.data$year,.data$conf) %>% 
  dplyr::summarize(metric = mean(metric)) %>% 
  dplyr::ungroup() %>% 
  dplyr::rename(team = .data$conf)

# We will create a third rtgs dataset for Notre Dame
rtgs_nd <- rtgs %>% 
  filter(team == team1) %>% 
  arrange(-.data$year, .data$rk) %>% 
  select(year, team, metric)

# combine the two datasets using rbind
plot_data <- rbind(rtgs_nd, rtgs_acc)

plot_data <- rtgs_nd %>% 
  mutate(metric_1 = metric) %>% 
  left_join(rtgs_acc %>% 
              select(.data$year, .data$metric),
            by=c("year"),suffix=c("","_2"))  
plot_data <- plot_data %>% 
  mutate(
    metric = round(metric,1),
    metric_1 = round(metric_1,1),
    metric_2 = round(metric_2,1)
  ) %>% 
  arrange(.data$year)

plot_data$Color_1 = Color1
plot_data$Color_2 = Color2

logo_url <- "https://raw.githubusercontent.com/saiemgilani/hoopR/master/man/figures/logo.png"
z <- tempfile()
download.file(logo_url,z,mode="wb")
m <- png::readPNG(z)
img <- matrix(rgb(m[,,1],m[,,2],m[,,3], m[,,4] ), nrow=dim(m)[1]) #0.2 is alpha
rast <- grid::rasterGrob(img, interpolate = T)

plot_data <- plot_data %>% 
  mutate(logo_1 = "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
         logo_2 = "https://a.espncdn.com/i/teamlogos/ncaa_conf/500/1.png?transparent=true&w=35&h=35") %>% arrange(year)
# points for plotting
x_max <- 2020
x_lab_min <- 2010 - 3
x_lab_max <- x_max + 2
x_score <- 2 + x_max
```
## Plotting
```{r}
draw_frame <- function(year)
{
  yr <- year
  # frame data
  frm_data <- plot_data %>% 
    filter(.data$year <= yr)
  
  # output quarter changes
  if (nrow(frm_data %>% filter(year == max(.data$year))) == 1)
  {
    print(glue::glue("Plotting AdjEM in Year: {max(frm_data$year)}"))
  }
  
  # plot
  frm_plot <- frm_data %>% 
    ggplot(aes(x = year, y = metric, group=team))+
    theme_minimal()+
    geom_vline(xintercept = c(2010, x_max), color = "#5555AA")+
    geom_segment(x = 2010, xend = 2020, y = 0, yend = 0, size = 0.75)+
    geom_image(x = x_score-1, y = 24, image = frm_data$logo_1, size = 0.09, asp = 1.5)+
    geom_image(x = x_score-1, y = 2, image = frm_data$logo_2, size = 0.12, asp = 1.5)+
    geom_image(aes(x = year, y = metric_1, image = logo_1),  size = .03, asp = 1.5)+
    geom_image(aes(x = year, y = metric_2, image = logo_2),  size = .06, asp = 1.5)+
    annotation_custom(grob = rast, xmin=2017, xmax=2020, ymin=-2, ymax=-20)+
    geom_line(aes(x = year, y = metric_1, color = Color1), size = 1)+
    geom_line(aes(x = year, y = metric_2, color = Color2), size = 1)+
    scale_color_manual(values = c(Color1, Color2))+
    scale_x_continuous(breaks = seq(2010, 2020, 1),
                       minor_breaks = NULL,
                       limits = c(2009.5, x_max + 2)) +
    scale_y_continuous(breaks = seq(-20, 35, 5),
                       minor_breaks = NULL,
                       limits = c(-21, 36)) +
    coord_cartesian(clip = "off",expand = FALSE) +
    xlab("") +
    ylab("") +
    labs(title = glue::glue("{team1} and {team2} \n{full_metric} Chart - {min(plot_data$year)}-{max(plot_data$year)}"),
         caption = "Data from kenpom.com | Visualization by @SaiemGilani") +
    theme(legend.position = "none",
          axis.title.x = element_text(size = 18, family = "sans", face = 'bold', color = "#3D1A22"),
          axis.text.x = element_text(size = 12, family = "sans", face = 'bold', color = "#3D1A22"),
          axis.title.y = element_text(size = 18, family = "sans", face = 'bold', color = "#3D1A22"),
          axis.text.y = element_text(size = 14, family = "sans", face = 'bold', color = "#3D1A22"),
          plot.title = element_text(size = 16, family = "sans", face = 'bold', color = "#3D1A22"),
          plot.subtitle = element_text(size = 14, family = "sans", face = 'bold', color = "#3D1A22"),
          plot.caption = element_text(size = 14, family = "sans", face = 'bold', color = "#3D1A22",hjust=0.5),
          panel.background = element_rect(fill = "snow"),
          plot.background = element_rect(fill = "#00AFDC"))
  
  # score display 
  metric1 <- tail(frm_data$metric_1, n=1)
  metric2 <- tail(frm_data$metric_2, n=1)
  
  # clock display
  Year <- case_when(
    max(frm_data$year) == 2010 ~ "2010" ,
    max(frm_data$year) == 2011 ~ "2011" ,
    max(frm_data$year) == 2012 ~ "2012" ,
    max(frm_data$year) == 2013 ~ "2013" ,
    max(frm_data$year) == 2014 ~ "2014" ,
    max(frm_data$year) == 2015 ~ "2015" ,
    max(frm_data$year) == 2016 ~ "2016" ,
    max(frm_data$year) == 2017 ~ "2017" ,
    max(frm_data$year) == 2018 ~ "2018" ,
    max(frm_data$year) == 2019 ~ "2019" ,
    max(frm_data$year) == 2020 ~ "2020" ,
    TRUE ~ as.character(max(frm_data$year))
  )
  
  # add score and clock to plot
  frm_plot <- frm_plot + 
    annotate("text", x = x_score-1, y = 16, label = metric1, color = Color1, size = 8) +
    annotate("text", x = x_score-1, y = -4, label = metric2, color = Color2, size = 8) +
    annotate("text", x = x_score-1, y = 8, label = Year, color = "#000000", size = 7)
  
  # label key moments
  # frm_labels <- frm_data %>% 
  #   filter(text != "")
  # frm_plot <- frm_plot +
  #   geom_point(frm_labels, mapping = aes(x = Year, y = AdjEM),
  #              color = "#000000", size = 2, show.legend = FALSE) +
  #   geom_segment(frm_labels, mapping = aes(x = x_text, xend = s, y = y_text, yend = wp),
  #                linetype = "dashed", color = "#000000", na.rm=TRUE) +
  #   geom_label(frm_labels, mapping = aes(x = x_text, y = y_text, label = text),
  #              size = 3, color = "#000000", na.rm = TRUE, alpha = 0.8)
  
  # plot the frame
  plot(frm_plot, width = 12.5, height = 6.47, dpi = 500)
}

draw_gif <- function()
{
  lapply(plot_data$year, function(year)
  { 
    draw_frame(year)
  })
  print("Plotting frames for pause")
  replicate(3, draw_frame(max(plot_data$year)))
  print("Assembling plots into a GIF")
}

saveGIF(draw_gif(), interval = 1, movie.name = glue::glue("animated_{metric}.gif"),
        ani.width = 960, ani.height = 540, ani.res = 110)
```

